/** Validates that a column name is in the allowlist. Prevents SQL injection via dynamic column names. */
export function validateColumn(col: string, allowlist: ReadonlySet<string>): string {
  if (!allowlist.has(col)) throw new Error(`Invalid column name: ${col}`);
  return col;
}

export const SCORE_COLUMNS = new Set([
  'id',
  'scorer_id',
  'trace_id',
  'span_id',
  'run_id',
  'scorer',
  'preprocess_step_result',
  'extract_step_result',
  'analyze_step_result',
  'score',
  'reason',
  'metadata',
  'preprocess_prompt',
  'extract_prompt',
  'generate_score_prompt',
  'generate_reason_prompt',
  'analyze_prompt',
  'reason_prompt',
  'input',
  'output',
  'additional_context',
  'request_context',
  'entity_type',
  'entity',
  'entity_id',
  'source',
  'resource_id',
  'thread_id',
  'structured_output',
  'created_at',
  'updated_at',
]) as ReadonlySet<string>;

export const EXPERIMENT_COLUMNS = new Set([
  'id',
  'name',
  'description',
  'metadata',
  'dataset_id',
  'dataset_version',
  'target_type',
  'target_id',
  'status',
  'total_items',
  'succeeded_count',
  'failed_count',
  'skipped_count',
  'started_at',
  'completed_at',
  'created_at',
  'updated_at',
]) as ReadonlySet<string>;

export const EXPERIMENT_RESULT_COLUMNS = new Set([
  'id',
  'experiment_id',
  'item_id',
  'item_dataset_version',
  'input',
  'output',
  'ground_truth',
  'error',
  'started_at',
  'completed_at',
  'retry_count',
  'trace_id',
  'created_at',
]) as ReadonlySet<string>;

export const DATASET_COLUMNS = new Set([
  'id',
  'name',
  'description',
  'metadata',
  'input_schema',
  'ground_truth_schema',
  'request_context_schema',
  'version',
  'created_at',
  'updated_at',
]) as ReadonlySet<string>;

export const AI_SPAN_COLUMNS = new Set([
  'id',
  'trace_id',
  'span_id',
  'parent_span_id',
  'name',
  'scope',
  'span_type',
  'is_event',
  'started_at',
  'ended_at',
  'attributes',
  'metadata',
  'links',
  'input',
  'output',
  'error',
  'tags',
  'entity_type',
  'entity_id',
  'entity_name',
  'parent_entity_type',
  'parent_entity_id',
  'parent_entity_name',
  'root_entity_type',
  'root_entity_id',
  'root_entity_name',
  'run_id',
  'thread_id',
  'resource_id',
  'request_context',
  'source',
  'user_id',
  'organization_id',
  'session_id',
  'request_id',
  'environment',
  'service_name',
  'experiment_id',
  'created_at',
  'updated_at',
]) as ReadonlySet<string>;
