import { boolean, index, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const aiSpans = pgTable(
  'ai_spans',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    traceId: text('trace_id').notNull(),
    spanId: text('span_id').notNull(),
    parentSpanId: text('parent_span_id'),
    name: text('name').notNull(),
    scope: jsonb('scope'),
    spanType: text('span_type').notNull(),
    isEvent: boolean('is_event').notNull().default(false),
    startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
    endedAt: timestamp('ended_at', { withTimezone: true }),
    attributes: jsonb('attributes'),
    metadata: jsonb('metadata').$type<Record<string, unknown>>(),
    links: jsonb('links'),
    input: jsonb('input'),
    output: jsonb('output'),
    error: jsonb('error'),
    tags: jsonb('tags'),
    entityType: text('entity_type'),
    entityId: text('entity_id'),
    entityName: text('entity_name'),
    parentEntityType: text('parent_entity_type'),
    parentEntityId: text('parent_entity_id'),
    parentEntityName: text('parent_entity_name'),
    rootEntityType: text('root_entity_type'),
    rootEntityId: text('root_entity_id'),
    rootEntityName: text('root_entity_name'),
    runId: text('run_id'),
    threadId: text('thread_id'),
    resourceId: text('resource_id'),
    requestContext: jsonb('request_context'),
    source: text('source'),
    userId: text('user_id'),
    organizationId: text('organization_id'),
    sessionId: text('session_id'),
    requestId: text('request_id'),
    environment: text('environment'),
    serviceName: text('service_name'),
    experimentId: text('experiment_id'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  },
  (table) => [
    index('ai_spans_trace_id_idx').on(table.traceId),
    index('ai_spans_name_started_at_idx').on(table.name, table.startedAt),
    index('ai_spans_entity_type_entity_id_idx').on(table.entityType, table.entityId),
    index('ai_spans_run_id_idx').on(table.runId),
  ],
);
